# Geometric Progression on a matrix- Alexandre-Theophile Vandermonde method

In [44]:
import numpy as np
def power(input,N):
    shpeofvector=input.shape
    for i in range(N) :
        arr1=np.array([np.power(input,N-i-1)])
        if i == 0 :
            concatarr=arr1.T
        else :
            concatarr=np.hstack((concatarr,arr1.T))
    return concatarr
print("The Alexandre-Theophile Vandermonde Geometric Progression")
inp = np.array([1,2,3,4])
res= power(inp,3)
print("The matrix with geometric progession is")
print(res)

The Alexandre-Theophile Vandermonde Geometric Progression
The matrix with geometric progession is
[[ 1  1  1]
 [ 4  2  1]
 [ 9  3  1]
 [16  4  1]]


#  MOVING AVERAGE OF AN ARRAY

In [76]:
def movingavg(input,k):
    mvngavg=[]
    for j in range(input.shape[0]-k+1):
        total=0    
        for i in range(j,j+k):
            total+=inp[i]
        mvngavg.append(total/k)
    mvngavgarr=np.array(mvngavg)
    return mvngavgarr

inp=np.array([3,5,7,2,8,10,11,65,72,81,99,100,150])
print("Input Array \n",inp)
print( '-'*75, "\n The moving average for the input array  with the window of 3 is \n",'-'*75)
np.set_printoptions(precision=2)
print(movingavg(inp,3))

Input Array 
 [  3   5   7   2   8  10  11  65  72  81  99 100 150]
--------------------------------------------------------------------------- 
 The moving average for the input array  with the window of 3 is 
 ---------------------------------------------------------------------------
[  5.     4.67   5.67   6.67   9.67  28.67  49.33  72.67  84.    93.33
 116.33]
